version: "2"
services:
        rabbitmq:
                image: rabbitmq
                container_name: rabbitmq
                expose:
                        - "5672"
                networks:
                        - rabbitmq
                environment:
                        RABBITMQ_DEFAULT_USER: rabbitmq
                        RABBITMQ_DEFAULT_PASS: rabbitmq
                hostname: rabbitmq

        redis:
                image: redis
                container_name: redis
                expose:
                        - "6379"
                networks:
                        - redis

        mongodb:
                image: mongo
                container_name: mongodb
                expose:
                        - "27017"
                volumes:
                        - ./mongo/script/:/script/
                        - ./mongo/data/:/data/db/
                networks:
                        - mongodb
                command: ["--auth", "--storageEngine", "wiredTiger"]

        spider:
                build:
                        context: .
                        dockerfile: Dockerfile-spider
                container_name: spider
                depends_on:
                        - rabbitmq
                        - redis
                        - mongodb
                networks:
                        - rabbitmq
                        - redis
                        - mongodb
                links:
                        - rabbitmq
                        - redis
                        - mongodb
                volumes:
                        - ./spider/:/spider/
                command: su -m spider -c "celery -A task.spider worker -l info"

        gw:
                build:
                        context: .
                        dockerfile: Dockerfile-gw
                container_name: gw
                ports:
                        - "8001:8001"
                depends_on:
                        - rabbitmq
                        - redis
                        - mongodb
                networks:
                        - gw
                        - rabbitmq
                        - redis
                        - mongodb
                links:
                        - rabbitmq
                        - redis
                        - mongodb
                volumes:
                        - ./spider/:/spider/
                command: su -m gw -c "uwsgi --ini-paste uwsgi.ini"

        www:
                build:
                        context: .
                        dockerfile: Dockerfile-www
                container_name: www
                networks:
                        - mongodb
                        - gw
                        - www
                expose:
                        - "8000"
                volumes:
                        - ./www/:/www/
                command: su -m www -c "uwsgi --ini-paste uwsgi.ini"

        nginx:
                image: nginx
                container_name: nginx
                depends_on:
                        - www
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
                        - ./nginx/www.conf:/etc/nginx/www.conf:ro
                        - ./www/static/:/www/static/:ro
                        - ./www/fonts/:/www/fonts:ro
                        - /var/cache/:/var/cache/
                networks:
                        - www
                ports:
                        - "80:80"
                        - "443:443"

networks:
        gw:
                driver: bridge
        rabbitmq:
                driver: bridge
        redis:
                driver: bridge
        mongodb:
                driver: bridge
        www:
                driver: bridge
