version: "3"

services:
        redis:
                image: redis
                container_name: redis
                sysctls:
                        net.core.somaxconn: 511
                expose:
                        - "6379"
                networks:
                        - redis

        mongodb:
                image: mongo
                container_name: mongodb
                expose:
                        - "27017"
                environment:
                        MONGO_INITDB_ROOT_USERNAME: admin
                        MONGO_INITDB_ROOT_PASSWORD: admin
                volumes:
                        - ./mongo/script/:/script/
                        - ./mongo/data/:/data/db/
                        - ./mongo/dump/:/dump/
                        - ./mongo/init/:/docker-entrypoint-initdb.d/
                networks:
                        - mongodb
                command: ["--auth", "--storageEngine", "wiredTiger"]

        spider:
                build:
                        context: spider/
                container_name: spider
                depends_on:
                        - redis
                        - mongodb
                expose:
                        - "50051"
                networks:
                        - spider
                        - redis
                        - mongodb
                links:
                        - redis
                        - mongodb
                volumes:
                        - ./spider/:/spider/
                working_dir: /spider/src/
                command: ["python3", "server.py"]

        www:
                build:
                        context: www/
                container_name: www
                depends_on:
                        - spider
                networks:
                        - spider
                        - mongodb
                        - www
                links:
                        - spider
                        - mongodb
                expose:
                        - "8000"
                volumes:
                        - ./www/:/www/
                command: ["uwsgi", "--ini-paste", "uwsgi.ini"]

        envoy:
                build:
                        context: envoy/
                container_name: envoy
                depends_on:
                        - spider
                networks:
                        - spider
                links:
                        - spider
                ports:
                        - "50051:50051"
                command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml"]

        nginx:
                image: nginx
                container_name: nginx
                depends_on:
                        - www
                        - spider
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
                        - ./nginx/www.conf:/etc/nginx/www.conf:ro
                        - ./www/src/static/:/www/static/:ro
                networks:
                        - www
                        - spider
                links:
                        - www
                        - spider
                ports:
                        - "80:80"
                        - "8080:8080"

networks:
        spider:
                driver: bridge
        redis:
                driver: bridge
        mongodb:
                driver: bridge
        www:
                driver: bridge
