version: "2"
services:
        www:
                build: .
                container_name: www
                networks:
                        - spider_mongodb
                        - spider_spider
                        - www
                expose:
                        - "8000"
                external_links:
                        - spider
                        - mongodb
                volumes:
                        - ./:/www/
                command: su -m www -c "uwsgi --ini-paste uwsgi.ini"

        nginx:
                image: nginx
                container_name: nginx
                depends_on:
                        - www
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
                        - ./nginx/www.conf:/etc/nginx/www.conf:ro
                        - ./static/:/www/static/:ro
                        - ./fonts/:/www/fonts:ro
                        - /etc/letsencrypt/archive/wartalker.me:/cert/:ro
                networks:
                        - www
                ports:
                        - "80:80"
                        - "443:443"

networks:
        spider_spider:
                external: true
        spider_mongodb:
                external: true
        www:
                driver: bridge
