version: "2"
services:
        redis:
                image: redis
                container_name: redis
                expose:
                        - "6379"
                networks:
                        - redis

        mongodb:
                image: mongo
                container_name: mongodb
                expose:
                        - "27017"
                volumes:
                        - ./script:/script:ro
                        - ./mongodb/:/data/db
                        - ~/db/:/back/
                networks:
                        - mongodb

        spider:
                build: .
                container_name: spider
                depends_on:
                        - redis
                        - mongodb
                networks:
                        - redis
                        - mongodb
                links:
                        - redis
                        - mongodb
                volumes:
                        - ./:/spider/
                command: su -m spider -c "celery -A task.spider worker -l info"

        gw:
                build: .
                container_name: gw
                ports:
                        - "8001:8001"
                depends_on:
                        - redis
                networks:
                        - gw
                        - redis
                links:
                        - redis
                volumes:
                        - ./:/spider/
                command: su -m spider -c "uwsgi --ini-paste uwsgi.ini"


networks:
        gw:
                driver: bridge
        redis:
                driver: bridge
        mongodb:
                driver: bridge
