version: "2"
services:
        redis:
                image: redis
                container_name: redis
                expose:
                        - "6379"
                networks:
                        - redis

        mongodb:
                image: mongo
                container_name: mongodb
                expose:
                        - "27017"
                volumes:
                        - ./script:/script:ro
                        - ./mongodb/:/data/db
                        - ~/db/:/back/
                networks:
                        - mongodb

        spider:
                build: .
                container_name: spider
                ports:
                        - "8001:8001"
                depends_on:
                        - redis
                        - mongodb
                networks:
                        - spider
                        - redis
                        - mongodb
                links:
                        - redis
                        - mongodb
                volumes:
                        - ./:/spider/
                command:  bash -c '([ -f /var/run/spider/spider.pid ] && rm /var/run/spider/spider.pid || echo "no pid file found") && su -m spider -c "celery multi start spiderjob -A task.spider --pidfile=/var/run/spider/spider.pid --logfile=/var/log/spider/spider.log --loglevel=INFO" && su -m spider -c "uwsgi --ini-paste uwsgi.ini"'

networks:
        spider:
                driver: bridge
        redis:
                driver: bridge
        mongodb:
                driver: bridge
